version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile.dev
    volumes:
      - ./apps/api:/app/apps/api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"