### STAGE: 1 ###
FROM golang:1.19 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/apps/api
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hero-ai-app .

### STAGE 2 ###
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/apps/api/hero-ai-app /hero-ai-app
EXPOSE 8080
CMD ["/hero-ai-app"]
